/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package persamaan;

import javax.swing.JOptionPane;



/**
 *
 * @author fatiq
 */
public class Persamaan extends javax.swing.JPanel {

    /**
     * Creates new form Sapes
     */
    public Persamaan() {
        initComponents();
    }
    public int a;
    public int b;
    public int c;
    public int x1;
    public int x2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_contenMenu = new javax.swing.JPanel();
        lb_3 = new javax.swing.JLabel();
        tf_a = new javax.swing.JTextField();
        tf_0 = new javax.swing.JTextField();
        tf_c = new javax.swing.JTextField();
        tf_b = new javax.swing.JTextField();
        lb_x4 = new javax.swing.JLabel();
        lb_hasil1 = new javax.swing.JLabel();
        pn_k2 = new javax.swing.JPanel();
        lb_hasil = new javax.swing.JLabel();
        lb_2 = new javax.swing.JLabel();
        lb_x2 = new javax.swing.JLabel();
        tf_x2 = new javax.swing.JTextField();
        lb_1 = new javax.swing.JLabel();
        lb_x1 = new javax.swing.JLabel();
        tf_x1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_cara = new javax.swing.JTextArea();
        lb_judul = new javax.swing.JLabel();
        btn_h1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_h = new javax.swing.JButton();

        pn_contenMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lb_3.setText("2");
        pn_contenMenu.add(lb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 20, -1));

        tf_a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_aFocusLost(evt);
            }
        });
        pn_contenMenu.add(tf_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, -1));

        tf_0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_0FocusLost(evt);
            }
        });
        pn_contenMenu.add(tf_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 50, -1));

        tf_c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_cFocusLost(evt);
            }
        });
        pn_contenMenu.add(tf_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 50, -1));

        tf_b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_bFocusLost(evt);
            }
        });
        pn_contenMenu.add(tf_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 50, -1));

        lb_x4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lb_x4.setText("X  +        X+        =");
        pn_contenMenu.add(lb_x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, -1));

        lb_hasil1.setBackground(new java.awt.Color(255, 255, 255));
        lb_hasil1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lb_hasil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hasil1.setText("hasil");
        pn_contenMenu.add(lb_hasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 390, -1));

        pn_k2.setBackground(new java.awt.Color(255, 255, 255));

        lb_hasil.setBackground(new java.awt.Color(255, 255, 255));
        lb_hasil.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lb_hasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hasil.setText("hasil");

        lb_2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lb_2.setText("2");

        lb_x2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lb_x2.setText("X   =");

        lb_1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lb_1.setText("1");

        lb_x1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lb_x1.setText("X   =");

        ta_cara.setColumns(20);
        ta_cara.setRows(5);
        jScrollPane1.setViewportView(ta_cara);

        lb_judul.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        lb_judul.setText("Persamaan Kuadrat");

        btn_h1.setText("H");

        javax.swing.GroupLayout pn_k2Layout = new javax.swing.GroupLayout(pn_k2);
        pn_k2.setLayout(pn_k2Layout);
        pn_k2Layout.setHorizontalGroup(
            pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_k2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_k2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_k2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_k2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(tf_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_k2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_h1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(pn_k2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_judul)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pn_k2Layout.setVerticalGroup(
            pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_k2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_judul)
                .addGap(39, 39, 39)
                .addGroup(pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_x1)
                    .addComponent(lb_x2)
                    .addGroup(pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_h1))
                    .addGroup(pn_k2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pn_k2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_1)
                            .addComponent(lb_2))))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lb_hasil)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pn_contenMenu.add(pn_k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 430, 490));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        pn_contenMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 390, 310));

        btn_h.setText("H");
        btn_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hActionPerformed(evt);
            }
        });
        pn_contenMenu.add(btn_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_contenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_contenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_aFocusLost
        try{
            a = Integer.parseInt(tf_a.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukkan input variabel dengan benar");
            tf_a.setText("");
        }
    }//GEN-LAST:event_tf_aFocusLost

    private void tf_bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_bFocusLost
        try{
            b = Integer.parseInt(tf_b.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukkan input variabel dengan benar");
            tf_b.setText("");
        }
    }//GEN-LAST:event_tf_bFocusLost

    private void tf_cFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cFocusLost
        try{
            c = c + Integer.parseInt(tf_c.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukkan input variabel dengan benar");
            tf_c.setText("");
        }
    }//GEN-LAST:event_tf_cFocusLost

    private void tf_0FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_0FocusLost
        try{
            c = c - Integer.parseInt(tf_c.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukkan input variabel dengan benar");
            tf_c.setText("");
        }
    }//GEN-LAST:event_tf_0FocusLost

    private void btn_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hActionPerformed
        int hasilX1 = -2147483648;
        int hasilX2 = -2147483648;
        int i = 0;
        while(i == 1){
            hasilX1++;
            if((hasilX1*hasilX2)==c  ){
                i++;
            }
            while(i==1){
                
            }
        }
    }//GEN-LAST:event_btn_hActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_h;
    private javax.swing.JButton btn_h1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_2;
    private javax.swing.JLabel lb_3;
    private javax.swing.JLabel lb_hasil;
    private javax.swing.JLabel lb_hasil1;
    private javax.swing.JLabel lb_judul;
    private javax.swing.JLabel lb_x1;
    private javax.swing.JLabel lb_x2;
    private javax.swing.JLabel lb_x4;
    private javax.swing.JPanel pn_contenMenu;
    private javax.swing.JPanel pn_k2;
    private javax.swing.JTextArea ta_cara;
    private javax.swing.JTextField tf_0;
    private javax.swing.JTextField tf_a;
    private javax.swing.JTextField tf_b;
    private javax.swing.JTextField tf_c;
    private javax.swing.JTextField tf_x1;
    private javax.swing.JTextField tf_x2;
    // End of variables declaration//GEN-END:variables

    
    
}
