/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import sapes.Sapes;

/**
 *
 * @author fatiq
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        bambang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_homeConten = new javax.swing.JPanel();
        pn_home = new javax.swing.JPanel();
        ScrolPn_home = new javax.swing.JScrollPane();
        pn_conten = new javax.swing.JPanel();

        pn_homeConten.setLayout(new java.awt.BorderLayout());

        pn_home.setBackground(new java.awt.Color(255, 255, 255));
        pn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_conten.setBackground(new java.awt.Color(255, 255, 255));
        pn_conten.setLayout(new javax.swing.BoxLayout(pn_conten, javax.swing.BoxLayout.X_AXIS));
        ScrolPn_home.setViewportView(pn_conten);

        pn_home.add(ScrolPn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1180, 540));

        pn_homeConten.add(pn_home, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_homeConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_homeConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrolPn_home;
    private javax.swing.JPanel pn_conten;
    private javax.swing.JPanel pn_home;
    private javax.swing.JPanel pn_homeConten;
    // End of variables declaration//GEN-END:variables

     private void addMenu(MenuHomeItem... menu){
        for(int i = 0; i < menu.length; i++){
            pn_conten.add(menu[i]);
            ArrayList<MenuHomeItem> subMenu = menu[i].getSubMenu();
            for(MenuHomeItem m : subMenu){
                addMenu(m);
            }
        }
        pn_conten.revalidate();
    }


    private void bambang() {
        ImageIcon iconSapes     = new ImageIcon(getClass().getResource("/img/NumberNexus_sapesHome.png"));
        ImageIcon iconMatriks   = new ImageIcon(getClass().getResource("/img/NumberNexus_matriksHome.png"));
        ImageIcon iconKuadrat   = new ImageIcon(getClass().getResource("/img/NumberNexus_kuadratHome.png"));
        ImageIcon iconPersaman  = new ImageIcon(getClass().getResource("/img/NumberNexus_persamaanHome.png"));
        ImageIcon iconLog       = new ImageIcon(getClass().getResource("/img/NumberNexus_logHome.png"));
        
        MenuHomeItem menuSapes        = new MenuHomeItem(iconSapes,null);
        MenuHomeItem menuMatriks      = new MenuHomeItem(iconMatriks,null);
        MenuHomeItem menuKuadrat      = new MenuHomeItem(iconKuadrat,null);
        MenuHomeItem menuPersamaan    = new MenuHomeItem(iconPersaman,null);
        MenuHomeItem menuLog          = new MenuHomeItem(iconLog,null);
        
        addMenu(menuSapes, menuMatriks,menuKuadrat, menuPersamaan, menuLog);
    }
}
