/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sapes;

import javax.swing.JOptionPane;

/**
 *
 * @author fatiq
 */
public class Balok extends javax.swing.JPanel {

    /**
     * Creates new form Persegi
     */
    public Balok() {
        initComponents();
    }
    public String y; 
    public int tinggi;
    public int panjang;
    public int lebar;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_contenMenu2 = new javax.swing.JPanel();
        hasil = new javax.swing.JLabel();
        v_lebar = new javax.swing.JTextField();
        pilih = new javax.swing.JComboBox<>();
        satuan = new javax.swing.JComboBox<>();
        ScrollPn = new javax.swing.JScrollPane();
        cara = new javax.swing.JTextArea();
        Judul = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        pn_ilustrasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        v_tinggi = new javax.swing.JTextField();
        v_panjang = new javax.swing.JTextField();

        pn_contenMenu2.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hasil.setBackground(new java.awt.Color(0, 0, 0));
        hasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasil.setText("hasil");
        pn_contenMenu2.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 240, -1));

        v_lebar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_lebar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                v_lebarFocusLost(evt);
            }
        });
        v_lebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_lebarActionPerformed(evt);
            }
        });
        pn_contenMenu2.add(v_lebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 140, 30));

        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Volume", "Luas Permukaan" }));
        pn_contenMenu2.add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 250, -1));

        satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "km", "hm", "dam", "m", "dm", "cm", "mm" }));
        satuan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                satuanFocusLost(evt);
            }
        });
        pn_contenMenu2.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 100, 110));

        cara.setColumns(20);
        cara.setRows(5);
        ScrollPn.setViewportView(cara);

        pn_contenMenu2.add(ScrollPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 250, 130));

        Judul.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        Judul.setText("Balok");
        pn_contenMenu2.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        pn_contenMenu2.add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 250, -1));

        pn_ilustrasi.setBackground(new java.awt.Color(255, 255, 255));
        pn_ilustrasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("0");
        pn_ilustrasi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 200, -1));

        jLabel4.setText("0");
        pn_ilustrasi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 200, -1));

        jLabel5.setText("Panjang =");
        pn_ilustrasi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel2.setText("Lebar =");
        pn_ilustrasi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/balok.png"))); // NOI18N
        pn_ilustrasi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel6.setText("Tinggi =");
        pn_ilustrasi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 30));

        jLabel7.setText("0");
        pn_ilustrasi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 40, 30));

        pn_contenMenu2.add(pn_ilustrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 490));

        v_tinggi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_tinggi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                v_tinggiFocusLost(evt);
            }
        });
        v_tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_tinggiActionPerformed(evt);
            }
        });
        pn_contenMenu2.add(v_tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 140, 30));

        v_panjang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        v_panjang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                v_panjangFocusLost(evt);
            }
        });
        v_panjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_panjangActionPerformed(evt);
            }
        });
        pn_contenMenu2.add(v_panjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_contenMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_contenMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_lebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_lebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_lebarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
            int x;
            if(pilih.getSelectedIndex()==0){
//            volume
              x = tinggi*panjang*lebar;
              hasil.setText("Volume = "+x+" "+y);
              cara.setText("Tinggi\t= "+tinggi+" "+y+"\nPanjang\t= "+panjang+y+"\nLebar\t= "+lebar+y+"\n \nVolume = tinggi * panjang * lebar\nVolume = "+tinggi+y+"*"+panjang+y+"*"+lebar+y+"\nVolume = "+x+" "+y);
            }
            else{
//            luas permukaan
              x = 2*((tinggi*panjang)+(tinggi*lebar)+(panjang*lebar));
              hasil.setText("Luas Permukaan = "+x+" "+y);
              cara.setText("Tinggi\t= "+tinggi+" "+y+"\nPanjang\t= "+panjang+y+"\nLebar\t= "+lebar+y+"\n \nLuas Permukaan = 2 * ((tinggi*panjang)+(tinggi*lebar)+(panjang*lebar))\nLuas Permukaan = 2*(("+tinggi+y+"*"+panjang+y+")+("+tinggi+y+"*"+lebar+y+")+("+panjang+y+"*"+lebar+y+"))\nLuas Permukaan = "+x+" "+y);
            }
    }//GEN-LAST:event_hitungActionPerformed

    private void satuanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_satuanFocusLost
        switch(satuan.getSelectedIndex()){
            case 0 :
                break;
            case 1 :
                y = "km";
                break;
            case 2 :
                y = "hm";
                break;
            case 3 :
                y = "dam";
                break;
            case 4 :
                y = "m";
                break;
            case 5 :
                y = "dm";
                break;
            case 6 :
                y = "cm";
                break;
            case 7 :
                y = "mm";
                break;
        }
        jLabel3.setText(lebar+" "+y);
        jLabel4.setText(panjang+" "+y);
        jLabel7.setText(tinggi+" "+y);
    }//GEN-LAST:event_satuanFocusLost

    private void v_lebarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_v_lebarFocusLost
        try{
        lebar = Integer.parseInt(v_lebar.getText());
        }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this, "Masukkan input lebar dengan benar");
          v_lebar.setText("");
        }
        jLabel3.setText(lebar+" "+y);
    }//GEN-LAST:event_v_lebarFocusLost

    private void v_tinggiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_v_tinggiFocusLost
        try{
        tinggi = Integer.parseInt(v_tinggi.getText());
        }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this, "Masukkan input tinggi dengan benar");
          v_tinggi.setText("");
        }
        jLabel7.setText(tinggi+" "+y);
    }//GEN-LAST:event_v_tinggiFocusLost

    private void v_tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_tinggiActionPerformed

    private void v_panjangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_v_panjangFocusLost
        try{
        panjang = Integer.parseInt(v_panjang.getText());
        }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this, "Masukkan input panjang dengan benar");
          v_panjang.setText("");
        }
        jLabel4.setText(panjang+" "+y);
    }//GEN-LAST:event_v_panjangFocusLost

    private void v_panjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_panjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_panjangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JScrollPane ScrollPn;
    private javax.swing.JTextArea cara;
    private javax.swing.JLabel hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JPanel pn_contenMenu2;
    private javax.swing.JPanel pn_ilustrasi;
    private javax.swing.JComboBox<String> satuan;
    private javax.swing.JTextField v_lebar;
    private javax.swing.JTextField v_panjang;
    private javax.swing.JTextField v_tinggi;
    // End of variables declaration//GEN-END:variables
}
