/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sapes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import menu.Home;
import menu.MenuItem;

/**
 *
 * @author fatiq
 */
public class Sapes extends javax.swing.JPanel {

    /**
     * Creates new form Sapes
     */
    public Sapes() {
        initComponents();
        bambang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_contenMenu = new javax.swing.JPanel();
        pn_menu = new javax.swing.JPanel();
        ScrolPn_menu = new javax.swing.JScrollPane();
        pn_scrolMenu = new javax.swing.JPanel();
        pn_conten = new javax.swing.JPanel();
        pn_contenMenu1 = new javax.swing.JPanel();

        pn_contenMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));

        pn_scrolMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_scrolMenu.setLayout(new javax.swing.BoxLayout(pn_scrolMenu, javax.swing.BoxLayout.Y_AXIS));
        ScrolPn_menu.setViewportView(pn_scrolMenu);

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addComponent(ScrolPn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addComponent(ScrolPn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pn_contenMenu.add(pn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pn_conten.setBackground(new java.awt.Color(255, 255, 255));

        pn_contenMenu1.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenMenu1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contenLayout = new javax.swing.GroupLayout(pn_conten);
        pn_conten.setLayout(pn_contenLayout);
        pn_contenLayout.setHorizontalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contenLayout.createSequentialGroup()
                .addComponent(pn_contenMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_contenLayout.setVerticalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contenLayout.createSequentialGroup()
                .addComponent(pn_contenMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pn_contenMenu.add(pn_conten, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 0, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_contenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_contenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrolPn_menu;
    private javax.swing.JPanel pn_conten;
    private javax.swing.JPanel pn_contenMenu;
    private javax.swing.JPanel pn_contenMenu1;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_scrolMenu;
    // End of variables declaration//GEN-END:variables

    
    private void addMenu(MenuItem... menu){
        for(int i = 0; i < menu.length; i++){
            pn_scrolMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for(MenuItem m : subMenu){
                addMenu(m);
            }
        }
        pn_scrolMenu.revalidate();
    }

    private void bambang() {
        ImageIcon iconPersegi           = new ImageIcon(getClass().getResource("/img/NumberNexus_persegi.png"));
        ImageIcon iconPersegiPanjang    = new ImageIcon(getClass().getResource("/img/NumberNexus_persegiPanjang.png"));
        ImageIcon iconLingkaran         = new ImageIcon(getClass().getResource("/img/NumberNexus_lingkaran.png"));
        ImageIcon iconKubus             = new ImageIcon(getClass().getResource("/img/NumberNexus_kubus.png"));
        ImageIcon iconBalok             = new ImageIcon(getClass().getResource("/img/NumberNexus_balok.png"));
        ImageIcon iconTabung            = new ImageIcon(getClass().getResource("/img/NumberNexus_tabung.png"));
        
        MenuItem menuPersegi        = new MenuItem(iconPersegi,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu1.removeAll();
                pn_contenMenu1.add(new Persegi());
                pn_contenMenu1.repaint();
                pn_contenMenu1.revalidate();
            }
        });
        MenuItem menuPersegiPanjang = new MenuItem(iconPersegiPanjang,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu1.removeAll();
                pn_contenMenu1.add(new PersegiPanjang());
                pn_contenMenu1.repaint();
                pn_contenMenu1.revalidate();
            }
        });
        MenuItem menuLingkaran      = new MenuItem(iconLingkaran,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu1.removeAll();
                pn_contenMenu1.add(new Lingkaran());
                pn_contenMenu1.repaint();
                pn_contenMenu1.revalidate();
            }
        });
        MenuItem menuKubus          = new MenuItem(iconKubus,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu1.removeAll();
                pn_contenMenu1.add(new Kubus());
                pn_contenMenu1.repaint();
                pn_contenMenu1.revalidate();
            }
        });
        MenuItem menuBalok          = new MenuItem(iconBalok,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu1.removeAll();
                pn_contenMenu1.add(new Balok());
                pn_contenMenu1.repaint();
                pn_contenMenu1.revalidate();
            }
        });
        MenuItem menuTabung         = new MenuItem(iconTabung,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu1.removeAll();
                pn_contenMenu1.add(new Tabung());
                pn_contenMenu1.repaint();
                pn_contenMenu1.revalidate();
            }
        });
        
        addMenu(menuPersegi,menuPersegiPanjang, menuLingkaran,menuKubus, menuBalok, menuTabung);
    }
}
