
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import matriks.Matriks;
import menu.Home;
import menu.MenuItem;
import persamaan.Persamaan;
import sapes.Sapes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fatiq
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bambang();
    }
    int xx, xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_top = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        watermark = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        pn_menu = new javax.swing.JPanel();
        ScrolPn_menu = new javax.swing.JScrollPane();
        pn_scrolMenu = new javax.swing.JPanel();
        pn_conten = new javax.swing.JPanel();
        pn_contenMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_top.setBackground(new java.awt.Color(51, 102, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NumberNexus2.png"))); // NOI18N

        watermark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NumberNexus_watermark.png"))); // NOI18N

        x.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_topLayout = new javax.swing.GroupLayout(pn_top);
        pn_top.setLayout(pn_topLayout);
        pn_topLayout.setHorizontalGroup(
            pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_topLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_topLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, Short.MAX_VALUE)
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(watermark))
                .addContainerGap())
        );
        pn_topLayout.setVerticalGroup(
            pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_topLayout.createSequentialGroup()
                .addGroup(pn_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_topLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logo))
                    .addGroup(pn_topLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(watermark)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(pn_top, java.awt.BorderLayout.PAGE_START);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));

        pn_scrolMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_scrolMenu.setLayout(new javax.swing.BoxLayout(pn_scrolMenu, javax.swing.BoxLayout.Y_AXIS));
        ScrolPn_menu.setViewportView(pn_scrolMenu);

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addComponent(ScrolPn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addComponent(ScrolPn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pn_menu, java.awt.BorderLayout.LINE_START);

        pn_conten.setBackground(new java.awt.Color(255, 255, 255));

        pn_contenMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenMenu.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contenLayout = new javax.swing.GroupLayout(pn_conten);
        pn_conten.setLayout(pn_contenLayout);
        pn_contenLayout.setHorizontalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contenLayout.createSequentialGroup()
                .addComponent(pn_contenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_contenLayout.setVerticalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contenLayout.createSequentialGroup()
                .addComponent(pn_contenMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pn_conten, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_contenMenu.add(new Home());
        pn_contenMenu.repaint();
        pn_contenMenu.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        dispose();
    }//GEN-LAST:event_xMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrolPn_menu;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel pn_conten;
    private javax.swing.JPanel pn_contenMenu;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_scrolMenu;
    private javax.swing.JPanel pn_top;
    private javax.swing.JLabel watermark;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables

    private void addMenu(MenuItem... menu){
        for(int i = 0; i < menu.length; i++){
            pn_scrolMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for(MenuItem m : subMenu){
                addMenu(m);
            }
        }
        pn_scrolMenu.revalidate();
    }

    private void bambang() {
        ImageIcon iconHome      = new ImageIcon(getClass().getResource("/img/NumberNexus_home.png"));
        ImageIcon iconSapes     = new ImageIcon(getClass().getResource("/img/NumberNexus_sapes.png"));
        ImageIcon iconMatriks   = new ImageIcon(getClass().getResource("/img/NumberNexus_matriks.png"));
        ImageIcon iconKuadrat   = new ImageIcon(getClass().getResource("/img/NumberNexus_kuadrat.png"));
        ImageIcon iconPersaman  = new ImageIcon(getClass().getResource("/img/NumberNexus_persamaan.png"));
        ImageIcon iconLog       = new ImageIcon(getClass().getResource("/img/NumberNexus_log.png"));
        
        MenuItem menuHome         = new MenuItem(iconHome,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu.removeAll();
                pn_contenMenu.add(new Home());
                pn_contenMenu.repaint();
                pn_contenMenu.revalidate();
            }
        });
        MenuItem menuSapes        = new MenuItem(iconSapes, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu.removeAll();
                pn_contenMenu.add(new Sapes());
                pn_contenMenu.repaint();
                pn_contenMenu.revalidate();
            }
        });
        MenuItem menuMatriks      = new MenuItem(iconMatriks,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu.removeAll();
                pn_contenMenu.add(new Matriks());
                pn_contenMenu.repaint();
                pn_contenMenu.revalidate();
            }
        });
        MenuItem menuKuadrat      = new MenuItem(iconKuadrat,null);
        MenuItem menuPersamaan    = new MenuItem(iconPersaman,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_contenMenu.removeAll();
                pn_contenMenu.add(new Persamaan());
                pn_contenMenu.repaint();
                pn_contenMenu.revalidate();
            }
        });
        MenuItem menuLog          = new MenuItem(iconLog,null);
        
        addMenu(menuHome,menuSapes, menuMatriks,menuKuadrat, menuPersamaan, menuLog);
    }
}

